### ISSUE TITLE
[PE-D][Tester A] User guide does not mention restrictions for names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#165]
Example: Indian names tend to use abbreviations such as s/o and d/o.

User Guide should explicitly state that its not allowed

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Justincjr/ped#1

**Comment by sayglenn** [comment]
Preliminary Comments:
- Agree with this.

Recommended Fix:
- Explain in user guide.
