### ISSUE TITLE
[PE-D][Tester A] Add person example in UG under installation guide not correct

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#167]
![image.png](https://raw.githubusercontent.com/Justincjr/ped/main/files/66f45643-4be8-4f78-b6e7-b2aa894f8e4f.png)

add command shown is incorrect

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Justincjr/ped#2

**Comment by sayglenn** [comment]
Preliminary Comments:
- Agree that this is outdated.

Recommended Fix:
- Change code to align with our implementation.
