### ISSUE TITLE
[PE-D][Tester C] User Guide references addressbook which may be confusing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#168]
The user guide references the word 'addressbook' in multiple areas. As a user, it may be confusing since your product is called ConTActs and the term addressbook may refer to something unknown.

Perhaps you could consider one of the following improvements,
1. replace all 'addressbook' with 'ConTActs', as that is the name of your product.
2. have a one-liner to explain that addressbook just means the contact list of ConTActs.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: rayray39/ped#2

**Comment by Domokunx** [comment]
Agreed.

Update UG such that all ConTActs is used instead of address book. Can double check if ConTActs is under glossary as well.
