### ISSUE TITLE
[PE-D][Tester A] AddressBook is used instead of app name ConTActs in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#169]
![image.png](https://raw.githubusercontent.com/Justincjr/ped/main/files/e1d2501e-53fa-4a9a-8b90-fd0a4713bc70.png)
ConTActs was used initially
Then subsequently AddressBook is used instead of ConTActs which can be very confusing for users

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Justincjr/ped#3

**Comment by sayglenn** [comment]
Preliminary Comments:
- Tester provides no context where AddressBook is used.

Recommended Fix:
- Review user guide to see if change is necessary.
