### ISSUE TITLE
[PE-D][Tester B] No restriction on length of phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#174]
There was no restriction on how long the phone number can be

![image.png](https://raw.githubusercontent.com/dez2003/ped/main/files/6fc3677f-2d85-4a92-9812-b8f2c259de07.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dez2003/ped#2

**Comment by sayglenn** [comment]
Preliminary Comments:
- Can probably be fixed similar to #223.

**Comment by Domokunx** [comment]
Extreme user behaviour, not considered bug
