### ISSUE TITLE
[PE-D][Tester E] Finding by name may result in the target person being displayed at last

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#176]
## Description
The command `find NAME` which finds all people who match the `NAME` may result in the target person being displayed at the end of the list.

## Steps to reproduce
1. Add a new person **Aaron Li**: `add n/Aaron Li i/E0000100 p/18765431 e/aaron@example.com`.
2. Find the person **Aaron Li`: `find Aaron Li`.

You should be able to observe that **Aaron Li** is displayed at the end of the list.

![image.png](https://raw.githubusercontent.com/wuzengfu/ped/main/files/2619762f-d199-44d8-a877-90de57c6017a.png)

## Suggestion
As a user, I want to find the person whose name can match **Aaron Li** and the person who can exactly match the name should come first. Since, the sample size is small, we can still find **Aaron Li** easily. However, if the list is long enough, there might be a case where a user has to scroll all the way down and check every outputed person to find **Aaron Li**.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: wuzengfu/ped#1

**Comment by Domokunx** [comment]
Valid concern. Planned Enhancement?

**Comment by sayglenn** [comment]
Perhaps our find was too broad.
