### ISSUE TITLE
[PE-D][Tester D] `mark` command resets my `find` filter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#187]
Reproduction:
1. `find david`
2. `mark 1 tut/2`
3. Notice how you are thrown back to the full listing

This behavior is quite disruptive when I have a lot of students and every time I find a specific student which I want to mark, it throws me back to the full listing, making me have to re-find my student to review the changes or do further actions.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: shotnothing/ped#9

**Comment by Domokunx** [comment]
Planned Enhancement to disable such behaviour?

**Comment by sayglenn** [comment]
I would technically say this is not a flaw, as we never intended to implement such a thing or advertised that such behaviour should exist. There are workarounds (manually going through the process) which do not really make this a bug. It is just an inconvenience, but no such unexpected behaviour occurs. Perhaps we just explain in the User Guide that such commands will reset the list.
