### ISSUE TITLE
[PE-D][Tester B] Composition symbol in diagram not used correctly

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#188]
![image.png](https://raw.githubusercontent.com/dez2003/ped/main/files/06c8ebd9-aecb-44a5-9762-185067f70c4a.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: dez2003/ped#3

**Comment by sayglenn** [comment]
Preliminary Comments:
- What

Recommended Fix:
- Please advise.

**Comment by Domokunx** [comment]
Likely one of those cases where "cascading deletion != composition"

I.E: We can independently instantiate these root notes without MainWindow node existing.
