### ISSUE TITLE
[PE-D][Tester D] Misleading error message when `tag/` is used instead of `t/`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#194]
Reproduction:
1. `add n/Jing Wen i/E0123456 p/12345678 e/jw@jw.com tag/something`
2. Output: `Emails should be of the format local-part@domain...`

Emails should be delimited by a space, so that the error of tag/ should be captured as invalid input, not with the misleading email error message.

![image.png](https://raw.githubusercontent.com/shotnothing/ped/main/files/b42a4488-b455-4b52-b8ae-9f52ffca5f94.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: shotnothing/ped#12

**Comment by Domokunx** [comment]
UG does not prompt user to use tag/ prefix in any location, this is not an expected input?

**Comment by yockcheng** [comment]
Not a legitimate user behaviour. User guide clearly states how to use the add command.

**Comment by sayglenn** [comment]
Closing as no fix required.
