### ISSUE TITLE
[PE-D][Tester D] `unmark` is a very misleading command name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#198]
The command `unmark` is misleading as it suggests resetting a marked status, whereas in this application, it is actually used to mark an student as absent. This naming convention may cause confusion, as users typically associate `unmark` with a neutral or reset action rather than a specific status change to `ABSENT.`

Suggestion to change the format of these commands to `mark present` and `mark absent`.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: shotnothing/ped#16

**Comment by Domokunx** [comment]
unmark command mentioned in UG.

ignore?

**Comment by sayglenn** [comment]
Critiquing our implementation does not fall under the scope of PE-D. I suggest we ignore this.

**Comment by sayglenn** [comment]
Closing as no fix required.
