### ISSUE TITLE
[PE-D][Tester E] Sort command error message can be improved

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#201]
## Description
The `sort 1` or `sort -1` commands can give more information about the usage of the command. For now, the output error message is `The field to sort by must be provided.`. However, as a first time user may not know what are some fields they can provide.

## Steps to reproduce
1. Enter the command `sort 1`.

You should be able to observe the error message `The field to sort by must be provided.`

![image.png](https://raw.githubusercontent.com/wuzengfu/ped/main/files/6f81cb14-c89c-4b96-91c1-d85c21596e33.png)

## Suggestion
A message such as `Example, sorting the list by name can be achieved via: sort 1 n/`. This would be more helpful for users to know what are some fields they can use for sorting.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wuzengfu/ped#6

**Comment by sayglenn** [comment]
No fix allowed. Closing.
