### ISSUE TITLE
[PE-D][Tester B] Misused Composition Symbol

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#204]
The composition symbol between AddressBook and UniquePersonList isn't used correctly.

![image.png](https://raw.githubusercontent.com/dez2003/ped/main/files/5eee348e-9a3d-4669-acf9-fe3ceb061673.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: dez2003/ped#5

**Comment by sayglenn** [comment]
Preliminary Comments:
- I'm unsure of the correctness of this.

Recommended Fix:
- Hope someone can check for me. Thank you.

**Comment by Domokunx** [comment]
Should be fine
