### ISSUE TITLE
[PE-D][Tester E] Incosistent UserGuide documentation on sort command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#205]
## Description
The `sort` command format specified in the UserGuide is `sort ORDER [n/][i/][tut/TUTORIAL]`. Note that there is **no space** in between the fields, this may confuse the user as they may try to enter command such as `sort 1 n/i/` instead of `sort 1 n/ i/`. However, the other commands such as `find` indeed have spaces in between the fields. Indeed, if a user follows the command format as specfied in the UserGuide, it fails.

![image.png](https://raw.githubusercontent.com/wuzengfu/ped/main/files/09d31949-1116-4943-9d9a-1daeda584d39.png)

## Steps to reproduce
1. Enter the command `sort 1 n/i/`.

You should be able to observe that the command fails which contradicate to the UserGuide given by the team.

![image.png](https://raw.githubusercontent.com/wuzengfu/ped/main/files/19b03554-7b55-44a0-8f26-3310100bb39a.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: wuzengfu/ped#7

**Comment by sayglenn** [comment]
Add the spaces.
