### ISSUE TITLE
[PE-D][Tester B] Wrong Arrow Direction for Inheritance

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#206]
The inheritance between Storage and AddressBookStorage/UserPrefsStorage has the inheritance arrow in the wrong direction
 
![image.png](https://raw.githubusercontent.com/dez2003/ped/main/files/1603f8da-9d51-4f94-bb61-8c74df2a9af9.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: dez2003/ped#6

**Comment by sayglenn** [comment]
Preliminary Comments:
- Let's check on this to ensure it's correct.
- This shouldn't be a medium bug? Low at most.

Recommended Fix:
- Check and amend if necessary.

**Comment by Domokunx** [comment]
![image](https://github.com/user-attachments/assets/3f7ea789-1041-4173-a57e-ee0f4c305ed6)
Diagram is correct. Storage class extends both classes.
