### ISSUE TITLE
[PE-D][Tester A] Refactor classes from ab3

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#216]
![image.png](https://raw.githubusercontent.com/Justincjr/ped/main/files/386ea293-4e0f-4e63-8d70-692806be4f1b.png)

Should refactor class to ConTActsParser

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: Justincjr/ped#9

**Comment by sayglenn** [comment]
Preliminary Comments:
- Should not be commenting on the inner workings of our program and how to change the implementation, but purely on its functionality and presented features.
- Does not fall in the category of bugs.

Recommended Fix:
- None.

**Comment by sayglenn** [comment]
Closing since no change required.
