### ISSUE TITLE
[PE-D][Tester A] Define TA in glossary

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#219]
![image.png](https://raw.githubusercontent.com/Justincjr/ped/main/files/9d24d0a2-132e-415c-941c-8dc0a62341e5.png)

To ensure that all stakeholders including those that may not be familiar with abbreviations used in NUS have a common understanding

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Justincjr/ped#10

**Comment by sayglenn** [comment]
Preliminary Comments:
- Not a medium bug. 
- Considering that the target audience is purely meant for users within NUS, it is unlikely they don't know what TA means. However, might still be good to define.

Recommended Fix:
- Define TA in glossary.
