### ISSUE TITLE
[PE-D][Tester C] Mismatch of student ID requirement in DG and error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T10-3/tp#222]
In the Developer Guide, under Glossary, the student ID is specified to take the format "eXXXXXXX" with a small letter e. However, when trying to add a new person with an id "e1234567", it is not allowed. Only student id with capital E is allowed. 

![add stud id small e.png](https://raw.githubusercontent.com/rayray39/ped/main/files/ee883c74-579f-4822-b6ad-ce5a713c0e0e.png)

![dg stud id small e.png](https://raw.githubusercontent.com/rayray39/ped/main/files/131a656f-bfe2-4fdf-9d3b-fd728a4f6907.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: rayray39/ped#10

**Comment by Domokunx** [comment]
Change DG to use capital E instead.

**Comment by sayglenn** [comment]
This is NOT high severity.
